### ISSUE TITLE
Address comments raised for Telechat

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-tcp#100]
Two comments from Jeff Haas raised as part of taking the document up on Telechat.

I have two small remaining comments:
- It might be nice to be mentioned in the acknowledgements. :-)
- It occurs to me that as the keychain extensions are defined that it might be desirable to protect them via if-feature.  Basically, what happens if tcp-ao or tcp-md5 aren't supported by the implementation?  I leave how this is dealt with up to the wisdom of the YANG doctors.

**Comment by michael-scharf** [comment]
The first comment is sorted out by PR #112. The second one is still TBD.

**Comment by michael-scharf** [comment]
The second comment is addressed as part of PR #113.
