### ISSUE TITLE
DISCUSS from Roman Danyliw

### ISSUE THREAD

**Issue by michael-scharf** [mjethanandani/ietf-tcp#104]
** B.2.  Thanks for providing an example of a TCP-AO configuration. 
Unfortunately, this isn’t a valid example example and it seems to be making
citations that don’t match.  Specifically:

-- “<crypto-algorithm>hmac-sha-256</crypto-algorithm>”

The algorithms usable by TCP-AO come from
https://www.iana.org/assignments/tcp-parameters/tcp-parameters.xhtml#tcp-parameters-3.
 Only SHA1 and AES128 are registered.  As far as I tell, the only work to add
SHA256 is in an unadopted and expired draft
(https://datatracker.ietf.org/doc/draft-nayak-tcp-sha2/).

As aside, I think the algorithm name would have been SHA-256 or SHA256 (no
HMAC).

--    Per the link to RFC9235:

    The following example demonstrates how to model a TCP-AO [RFC5925]
   configuration for the example in TCP-AO Test Vectors [RFC9235].  The
   IP addresses and other parameters are taken from the test vectors.

RFC9235 doesn’t use SHA256; and uses KeyID 61 and 84.  Different KeyIDs are
used in this example.  Which parameters are being used from the test-vector?

**Comment by mjethanandani** [comment]
> ** B.2. Thanks for providing an example of a TCP-AO configuration. Unfortunately, this isn’t a valid example example and it seems to be making citations that don’t match. Specifically:
> 
> -- “hmac-sha-256”
> 
> The algorithms usable by TCP-AO come from https://www.iana.org/assignments/tcp-parameters/tcp-parameters.xhtml#tcp-parameters-3. Only SHA1 and AES128 are registered. As far as I tell, the only work to add SHA256 is in an unadopted and expired draft (https://datatracker.ietf.org/doc/draft-nayak-tcp-sha2/).

Hmm. It turns out that the ietf-keychain module does not define AES128 as one of the crypto algorithms. I can add it this module, although I feel it is out of place for the TCP YANG model to add a crypto algorithm. The only justification is that TCP-AO uses it.

> 
> As aside, I think the algorithm name would have been SHA-256 or SHA256 (no HMAC).
> 
> -- Per the link to RFC9235:
> 
> ```
> The following example demonstrates how to model a TCP-AO [RFC5925]
> ```
> 
> configuration for the example in TCP-AO Test Vectors [RFC9235]. The IP addresses and other parameters are taken from the test vectors.
> 
> RFC9235 doesn’t use SHA256; and uses KeyID 61 and 84. Different KeyIDs are used in this example. Which parameters are being used from the test-vector?

Ok. Fixed the example to use AES128 and the key-ids from RFC 9235.

**Comment by michael-scharf** [comment]
Somehow the key-ids did not make it into branch ietf-08.

Therefore, I created a new PR #119 to fix this.

I also believe some further small additions would be useful to improve the TCP-AO modeling. See PR #119.

**Comment by michael-scharf** [comment]
Also, I actually don't understand why the TCP-AO example needs multiple key-chain entries. This just makes it more complex and opens room for questions, e.g., whether the same send-id and recv-id can be used in multiple entries.

**Comment by mjethanandani** [comment]
Hmm. There is only one key-chain. The other is only a reference to it.

**Comment by michael-scharf** [comment]
My comment is about _entries_ in the key-chain. So far, the example had two entries, and the differences between both were not exactly clear. Anyway, I think one entry would be sufficient as example.
