### ISSUE TITLE
DISCUSS from Paul Wouters

### ISSUE THREAD

**Issue by michael-scharf** [mjethanandani/ietf-tcp#109]
[ballot text incomplete as cloudflare triggers a weird refusal if I include a certain sentence, see Cloudflare Ray ID: 722aa6477e01a1db]

Thanks for the -07 changes in response to the various area reviews!

I still have two small discuss questions left which might be caused by a limited
understanding of the underlying yang model inclusions.

              1. For an application willing to accept both IPv4 and
                 IPv6 datagrams, the value of this object must be
                 ''h (a zero-length octet-string), with the value
                 of the corresponding 'type' object being
                 unknown (0).

              2. For an application willing to accept only IPv4 or
                 IPv6 datagrams, the value of this object must be
                 '0.0.0.0' or '::' respectively, with
                 'type' representing the appropriate address type.

#D1

To me, it seems very counter-intuitive that '' means (0.0.0.0 or ::). For
LISTEN, I find it concerning because it means that '' as a default means to
listen to any IP, rather than the more secure default of '' meaning 'none'.

Is it possible to have some kind of "None" default? (or is that achieved by
omission of this option?

#D2

Is it intended that this cannot be specified using names

**Comment by mjethanandani** [comment]
> [ballot text incomplete as cloudflare triggers a weird refusal if I include a certain sentence, see Cloudflare Ray ID: 722aa6477e01a1db]
> 
> Thanks for the -07 changes in response to the various area reviews!
> 
> I still have two small discuss questions left which might be caused by a limited understanding of the underlying yang model inclusions.
> 
> ```
>           1. For an application willing to accept both IPv4 and
>              IPv6 datagrams, the value of this object must be
>              ''h (a zero-length octet-string), with the value
>              of the corresponding 'type' object being
>              unknown (0).
> 
>           2. For an application willing to accept only IPv4 or
>              IPv6 datagrams, the value of this object must be
>              '0.0.0.0' or '::' respectively, with
>              'type' representing the appropriate address type.
> ```
> 
> #D1
> 
> To me, it seems very counter-intuitive that '' means (0.0.0.0 or ::). For LISTEN, I find it concerning because it means that '' as a default means to listen to any IP, rather than the more secure default of '' meaning 'none'.

These sentences are copied from TCP MIB. We have not created this definition on our own.

> 
> Is it possible to have some kind of "None" default? (or is that achieved by omission of this option?
> 
> #D2
> 
> Is it intended that this cannot be specified using names

Again, we are following TCP MIB language here.

**Comment by michael-scharf** [comment]
I am not aware of a good reason to change concepts established by the MIB.

Yet, the description could maybe be improved further. I have submitted PR #117 for that.

Other than PR #117, at least I don't think further changes are required.

**Comment by mjethanandani** [comment]
I agree. And I have gone ahead and approved PR#117.
