### ISSUE TITLE
COMMENT from Paul Wouters

### ISSUE THREAD

**Issue by michael-scharf** [mjethanandani/ietf-tcp#110]
#C1

It is unclear to me if '0.0.0.0' denotes the type inet:ip-address or
the type string with text value "0.0.0.0". I also worry that if this is
represented in C with a struct with union, that than it is unclear what
a zero'ed out struct is set to? The string or the v4 ANY or the v6 ANY ?
(I personally like enums to start from value 1 for that reason)

#C2

How is this option set when fully disabled (eg not listening on anything, only
willing to make an outgoing TCP connection). Is it by being omitted?

NITS:

listner -> listener

for TCP connection that -> for a TCP connection that

**Comment by michael-scharf** [comment]
The two nits are fixed by PR #112. The two comments are still TBD.

**Comment by mjethanandani** [comment]
> #C1
> 
> It is unclear to me if '0.0.0.0' denotes the type inet:ip-address or the type string with text value "0.0.0.0". I also worry that if this is represented in C with a struct with union, that than it is unclear what a zero'ed out struct is set to? The string or the v4 ANY or the v6 ANY ? (I personally like enums to start from value 1 for that reason)

RFC 7950 says: "a value is validated consecutively
   against each member type, in the order they are specified in the
   "type" statement, until a match is found.  The type that matched will
   be the type of the value for the node that was validated, and the
   encoding is interpreted according to the rules for that type."

First of all if the value is 0.0.0.0 of type ip-address, it is not going to match the type string. The zeroed out structure of this union would also be all zeroes, if the type is ip-address, with an indication of what type of value is stored in the structure, and will be an ASCII representation if the type is a string.

> 
> #C2
> 
> How is this option set when fully disabled (eg not listening on anything, only willing to make an outgoing TCP connection). Is it by being omitted?

I am not clear the context of this comment. Which line/paragraph in the draft does this comment apply to?

> 
> NITS:
> 
> listner -> listener
> 
> for TCP connection that -> for a TCP connection that

Thanks for taking care of these nits.

**Comment by michael-scharf** [comment]
Regarding C2: If the comment is related to the TCP listener list, IMHO no further action is needed. There will be no entry in that list for a TCP endpoint that is passively opening a connection, i.e., no listening.

As far as I can see, no further change is needed.
