### ISSUE TITLE
Add a length statement for addresses that are represented as a string

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-tcp#121]
For this part of the model

```
leaf address {
  type union {
    type string;
    type inet:ip-address;
  }
}
```

should be modified to:
```
leaf address {
  type union {
    type string {
      length "1..max;
    }
    type inet:ip-address;
  }
}
```
to address the following comment.

(ii) Add a length "0" restriction to the string type.

**Comment by michael-scharf** [comment]
Two questions come into my mind. Sorry if I miss something...

1/ How would ''h, i.e., a zero-length octet-string, be encoded in this union if the string must have at last length 1? As far as I understand inet:ip-address, this cannot be a zero-length string, right? In other words, is it really not required to allow 0 as length.

2/ I really wonder if "max" as upper limit is needed. That may also depend on question 1, though.

**Comment by mjethanandani** [comment]
> Two questions come into my mind. Sorry if I miss something...
> 
> 1/ How would ''h, i.e., a zero-length octet-string, be encoded in this union if the string must have at last length 1? As far as I understand inet:ip-address, this cannot be a zero-length string, right? In other words, is it really not required to allow 0 as length.

Good point. No there is no way to encode a zero-length octet string if the min is 1.

> 
> 2/ I really wonder if "max" as upper limit is needed. That may also depend on question 1, though.

If we do not need a min, a max of max does not make sense. As such, this is a non-issue and we can close it.

**Comment by michael-scharf** [comment]
I wonder if the original intention was actually to have a sting with max length 0 only...

AFAIKT, a string is only needed to encode '' with length 0. Strings with length > 0 should actually never occur, as they would be modeled by an ip-address...

Now, I don't know if YANG allows this:

> type string {
>       length "0;
>     }

Also, I am not sure whether it actually makes sense...
