### ISSUE TITLE
Should we add support for congestion control algorithm at a global level?

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-tcp#18]
The model has defined a congestion-control-algorithm at a per connection level as a 'config false' leaf. As discussed in the meeting today, we should consider a global configurable attribute for the algorithm.

If defined, it will be the default algorithm selected by the system. It can however be overridden by a per connection algorithm. This behavior should be also be described in the draft, and in the model.

In the model it can appear right after the description statement that says "TCP container".

**Comment by michael-scharf** [comment]
See PR#20
