### ISSUE TITLE
Should the model support statistics?

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-tcp#3]
The draft currently states that the module shall not support TCP statistics. It will be helpful to understand why.

**Comment by mjethanandani** [comment]
As a starting point, I was thinking of the following statistics to be supported.

- active-opens
- passive-opens
- attempt-fails
- establish-resets
- currently-established
- in-segments
- out-segments
- retransmitted-segments
- in-errors
- out-resets

**Comment by michael-scharf** [comment]
These stats already exist in the TCP MIB. I agree that stats existing in the TCP MIB could be added.

**Comment by mjethanandani** [comment]
It was agreed in the January 9, 2020 meeting that these statistics can be supported in the YANG model under a feature statement. Therefore, I will add a feature statement to that effect.

**Comment by mjethanandani** [comment]
See PR https://github.com/mjethanandani/ietf-tcp/pull/10.

**Comment by mjethanandani** [comment]
Resolved as part of https://github.com/mjethanandani/ietf-tcp/pull/10
