### ISSUE TITLE
Make reset of stats optional

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-tcp#49]
The model currently requires that implementations support reset of statistics. But that is not supported by all OS/platforms. Introduce a feature statement to make support coniditional.

**Comment by michael-scharf** [comment]
Comment during IETF 110 from Richard: I would like to have the reset in the YANG model, not optional. Implementation could cover limitations of base OS.

**Comment by mjethanandani** [comment]
Interesting perspective!

**Comment by mjethanandani** [comment]
> Comment during IETF 110 from Richard: I would like to have the reset in the YANG model, not optional. Implementation could cover limitations of base OS.

If something is defined in the model, implementations are required to implement the model or create a deviation for it. Deviations are generally frowned upon, unless there are good reasons to have them, e.g. hardware limitations.

So the question comes down to, should we make it optional to implement reset of statistics, or require that it be implemented. That implementation, as suggested by you, could be done in software by keeping a shadow copy of the statistics, and clearing the shadow copy everytime a reset is issued. In the worst case scenario, if an implementation cannot implement reset of statistics in software, they can deviate from the model.

Is this something we should present to the WG to decide?

**Comment by michael-scharf** [comment]
My understanding is that there was no pushback against Richard's comment, i.e., his suggestion to keep the action as mandatory seems to have support.

In that case, the draft should maybe outline how the action reset can easily be implemented even on systems not natively supporting it (at least hypothetically, that would be an issue on a system just using the TCP MIB). My proposed wording in #52 addresses this.

**Comment by michael-scharf** [comment]
Addressed by PR #53
