### ISSUE TITLE
Add support for TCP-AO?

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-tcp#5]
There is a requirement from BGP YANG model to be able to configure TCP-AO. To support that should this define a grouping for configuration of TCP-AO?

**Comment by mjethanandani** [comment]
Also, should that grouping refer to current-key and rnext-key as uint8 (an index) or as type binary (copy of the key).

**Comment by mjethanandani** [comment]
It was agreed in the meeting on 1/9/2020 that support for TCP-AO is one of the requirements driving this draft, therefore it needs to be supported. Changed the title to reflect that. From here onwards, this issue will track how TCP-AO will be supported.

**Comment by vmurgai** [comment]
My thoughts on yang definition for TCP AO:

list key_chain
{ 
	String id <Id for the key_chain e.g. “123” “234”>
        List key {                            
		int Identifier
		Uses ao_params
	}
}

grouping ao_params {
    Send_id
    Recv_id
    Crypto Algorithm
    Key string
    Lifetime
    Options
}

Notes:
All TCP sessions under same keychain would use the same ao_params (or mkt). Under a keychain, at one particular time, only one key is going to be used and selected. Each key is valid for its own defined lifetime.

**Comment by vmurgai** [comment]
I did see your question where you had asked about 'leafref " but unable to locate it now. 
Could you please point me to that.

**Comment by mjethanandani** [comment]
It is the pull request - https://github.com/mjethanandani/ietf-tcp/pull/11

**Comment by mjethanandani** [comment]
> My thoughts on yang definition for TCP AO:
> 
> list key_chain
> {
> String id <Id for the key_chain e.g. “123” “234”>
> List key {
> int Identifier
> Uses ao_params
> }
> }
> 
> grouping ao_params {
> Send_id
> Recv_id
> Crypto Algorithm
> Key string
> Lifetime
> Options
> }
> 
> Notes:
> All TCP sessions under same keychain would use the same ao_params (or mkt). Under a keychain, at one particular time, only one key is going to be used and selected. Each key is valid for its own defined lifetime.

Vishal, have you looked at the [ietf-key-chain](https://tools.ietf.org/html/rfc8177) model. You will find that most of these parameters are defined there.

**Comment by mjethanandani** [comment]
> I did see your question where you had asked about 'leafref " but unable to locate it now.
> Could you please point me to that.

It is the pull request - #11
