### ISSUE TITLE
Should congestion control algorithms be selectable?

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-tcp#6]
TCP supports several Congestion Control Algorithms (CCA), CUBIC, BBR, NewReno to name a few. Should the model define an identity for CCAs, and allow for them to be selected on a per connection basis?

**Comment by mjethanandani** [comment]
Two things should be noted here. Not all implementations will support all CCAs. Therefore each algorithm would have be defined with a feature statement, and if supported, could be made selectable in the model on a per connection basis.

**Comment by mjethanandani** [comment]
Should the CCA's be modeled as identities? Since the algorithms are evolving, it is better to model them as identities. They will be further controlled by feature statement.

**Comment by michael-scharf** [comment]
As discussed before, this is a non-trivial topic as there is a large number of algorithms and the algorithms continue to evolve. There are a couple of classes of widely used algorithms, but it is impossible to model algorithm details.

PR #15 implements a basic solution limited to algorithms described in RFCs.
