### ISSUE TITLE
Further review comments from Tom Petch

### ISSUE THREAD

**Issue by michael-scharf** [mjethanandani/ietf-tcp#64]
Copied from the TCPM list:

> all YANG import need a Normative Reference
> 
> I would like a more comprehensive comparison with RFC4022 - other I-D 
> have provided a table showing the objects or groups thereof which carry 
> across and those that do not.
> 
> You mention other models which model TCP - for me the most comprehensive 
> would be in I2NSF
> 
> 0..255 could be 0..max
> 
> MD5 needs calling out as no longer strong enough both in the YANG module 
> and in Security Considerations, perhaps making AO the default, perhaps 
> making MD5 deprecated.  The Security AD will do this if noone else does 
> but why make work for him?  opsawg-l3sm-l3nm and dhcpv6-yang went this 
> way recently
> 
> the statistics with their protocol detail need references even if every 
> one is 793bis
> 
> YANG 'action' could probably do with a NACM default deny-all
> 
> 5.1 This document registers two URIs...
> Really?
> 
> Examples should use documentation IP addresses
> 
> An IPv6 example might create a good impression
> 
> The convention for line wrap would be better for a reference to RFC8792
>

**Comment by mjethanandani** [comment]
> > I would like a more comprehensive comparison with RFC4022 - other I-D
> > have provided a table showing the objects or groups thereof which carry
> > across and those that do not.

@michael-scharf, do you mind taking a stab at this.

**Comment by mjethanandani** [comment]
> Copied from the TCPM list:
> 
> > all YANG import need a Normative Reference

Done

> > I would like a more comprehensive comparison with RFC4022 - other I-D
> > have provided a table showing the objects or groups thereof which carry
> > across and those that do not.

@michael-scharf, can you take a crack at this.

> > You mention other models which model TCP - for me the most comprehensive
> > would be in I2NSF

I do not know if there is any specific AI associated with this.

> > 0..255 could be 0..max

Fixed.

> > MD5 needs calling out as no longer strong enough both in the YANG module
> > and in Security Considerations, perhaps making AO the default, perhaps
> > making MD5 deprecated.  The Security AD will do this if noone else does
> > but why make work for him?  opsawg-l3sm-l3nm and dhcpv6-yang went this
> > way recently
opsawg-l3sm-l3nm does make references to MD5, both in text of the draft and in the Security Considerations section, but dhcpv6 does not. Neither does the model make tcp-ao as the default. @michael-scharf  or @vmurgai , can you take a stab of what text you want to move over.

> > the statistics with their protocol detail need references even if every
> > one is 793bis

Added.

> > YANG 'action' could probably do with a NACM default deny-all

Added

> > 5.1 This document registers two URIs...
> > Really?

I think he is referring to an older version of the draft.

> > Examples should use documentation IP addresses

Done.

> > An IPv6 example might create a good impression

Done.

> > The convention for line wrap would be better for a reference to RFC8792

Added.

**Comment by michael-scharf** [comment]
I can take care of the comparison to the TCP-MIB

**Comment by vmurgai** [comment]
Hi Mahesh,

Sure, I would take a look at:

MD5 needs calling out as no longer strong enough both in the YANG module
and in Security Considerations, perhaps making AO the default, perhaps
making MD5 deprecated. The Security AD will do this if noone else does
but why make work for him? opsawg-l3sm-l3nm and dhcpv6-yang went this
way recently
opsawg-l3sm-l3nm does make references to MD5, both in text of the draft and
in the Security Considerations section, but dhcpv6 does not. Neither does
the model make tcp-ao as the default. @michael-scharf
<https://github.com/michael-scharf> or @vmurgai <https://github.com/vmurgai> ,
can you take a stab of what text you want to move over


Regards,

Vishal.
