### ISSUE TITLE
Change connection identification?

### ISSUE THREAD

**Issue by michael-scharf** [mjethanandani/ietf-tcp#69]
There are some non-editorial comments in the review of Mohamed Boucadair (see https://mailarchive.ietf.org/arch/msg/tcpm/nNqEcdpw1nZ7UcsslR7AVCuhjn4/ and other TCPM list discussion):

One example is the connection list, specifically "local-address", "remote-address", "local-port", "remote-port":

Comment by Med: "This may not be easily augmented in the future to support MPTCP."

This may be correct. But MPTCP is clearly out-of-scope of this document, and a future MPTCP module may not have to use this list. Maybe one could come up with something more generic, but that would be a bigger change. I believe this can stay as-is and no change is needed. 

Other thoughts?

**Comment by mjethanandani** [comment]
I agree that MPTCP is not in scope of this draft. As such, any changes to try to accommodate the requirements for MPTCP are also scope of this draft. I would agree that we should close this issue.

**Comment by vmurgai** [comment]
Hi Michael, Mahesh,
IMHO, we could mention that MPTCP is out of the scope of this draft...thoughts?
Thanks
