### ISSUE TITLE
Further review by Med Boucadair

### ISSUE THREAD

**Issue by michael-scharf** [mjethanandani/ietf-tcp#74]
Review comments by Med Boucadair on TCPM list:

```
- Section 4

(1)
OLD: 
       reference
         "RFC XXXX, YANG Model for Transmission Control Protocol (TCP)
                    Configuration.";

NEW:
       reference
         "RFC XXXX: A YANG Model for Transmission Control Protocol (TCP)
                    Configuration";

(2)

Add "when set to true" in the description of almost all the Boolean nodes. 

(3)

I still don't think "forms the connection identifier" is accurate. The connection is identified by the 4-uple (which is captured in the key statement). You may consider simply: s/forms the connection identifier/of the connection. Another better approach would be, e.g.: 

OLD: 
 "Local address that forms the connection identifier.";
NEW:
 "Identifies the address that is used locally by an endpoint to bind the connection.";

OLD: 
 "Remote address that forms the connection identifier.";
NEW:
 "Identifies the address that is used by the peer endpoint to bind the connection.";

etc. 

- Make this change in 5.2: s/registrations are requested/registration is requested
- Update 5.2 to make it explicit that the module is not maintained by IANA: 

OLD:
      name:         ietf-tcp
      namespace:    urn:ietf:params:xml:ns:yang:ietf-tcp
      prefix:       tcp
      reference:    RFC XXXX

NEW:
      name:         ietf-tcp
      namespace:    urn:ietf:params:xml:ns:yang:ietf-tcp
      prefix:       tcp
      maintained by IANA: N
      reference:    RFC XXXX 

- I think you can remove the note in B.1
- remove "\" right after "</description>" in B.2
- As you are referring to RFC 8792, you need to add the 8792 header to adhere with the following (B.2):

======
...
   Text content that has been folded as specified by this strategy MUST
   adhere to the following structure.

7.1.1.  Header

   The header is two lines long.

   The first line is the following 36-character string; this string MAY
   be surrounded by any number of printable characters.  This first line
   cannot itself be folded.

   NOTE: '\' line wrapping per RFC 8792

   The second line is an empty line, containing only the end-of-line
   character sequence.  This line provides visual separation for
   readability.
=====

- B.2:

<!--
This example sets TCP-AO configuration parameters as
demonstrated by examples in draft-touch-tcpm-ao-test-vectors.
-->

Not sure why this I-D is cited here given the example does not echo an example from that I-D (e.g., same local/remote port, local address, etc.). Also, I was expecting to see an example that illustrates the use of send-id and recv-id.

If the citation is maintained, please make this change: 

s/demonstrated by examples in draft-touch-tcpm-ao-test-vectors/demonstrated by examples in I-D.ietf-tcpm-ao-test-vectors
```

**Comment by michael-scharf** [comment]
Pull request #73 should address all these issues (except for the note in B.1, which is added by default always in the script).

However, the comment on B.2 and PR #73 needs double-checking. @mjethanandani? @vmurgai?

**Comment by mahesh-arrcus** [comment]
I am ok with dropping the comment.

**Comment by vmurgai** [comment]
Hi Michael, Mahesh,

Based on my understanding, I think it would be good to keep a reference to AO-test vectors draft. 
So we could just replace the ID name to ID.ietf-tcpm-ao-test-vectors, as suggested by Med.

Thanks

**Comment by mjethanandani** [comment]
Hi @vmurgai, the issue that I see, and what Med has raised is that if you decide to cite the particular test vector draft, is that you then you have to follow the test vectors to the T, which our example does not. If you care to, I would suggest that you submit a separate PR with the example corrected that follows the test vector.

**Comment by michael-scharf** [comment]
> Hi Michael, Mahesh,
> 
> Based on my understanding, I think it would be good to keep a reference to AO-test vectors draft. So we could just replace the ID name to ID.ietf-tcpm-ao-test-vectors, as suggested by Med.
> 
> Thanks

That simple solution is already included in PR #73 - please check the commit.

**Comment by michael-scharf** [comment]
> Hi @vmurgai, the issue that I see, and what Med has raised is that if you decide to cite the particular test vector draft, is that you then you have to follow the test vectors to the T, which our example does not. If you care to, I would suggest that you submit a separate PR with the example corrected that follows the test vector.

Actually, I tried to align PR #73 with the test-vector ID. Just check the commit for PR #73.

We can either decide to align with test-vector, or not. If not, the comment can be dropped, but then we may need more text to explain the example.

Note that Med's review raises another aspect: Include send-id and recv-id in the example: This is clearly a resonable ask no matter whether the details are aligned with test-vectors or not.

And this raises the question how the corresponding key-chain looks like. See PR #73 for what I came up with so far.

**Comment by mjethanandani** [comment]
> > Hi @vmurgai, the issue that I see, and what Med has raised is that if you decide to cite the particular test vector draft, is that you then you have to follow the test vectors to the T, which our example does not. If you care to, I would suggest that you submit a separate PR with the example corrected that follows the test vector.
> 
> Actually, I tried to align PR #73 with the test-vector ID. Just check the commit for PR #73.
> 
> We can either decide to align with test-vector, or not. If not, the comment can be dropped, but then we may need more text to explain the example.
> 
> Note that Med's review raises another aspect: Include send-id and recv-id in the example: This is clearly a resonable ask no matter whether the details are aligned with test-vectors or not.
> 
> And this raises the question how the corresponding key-chain looks like. See PR #73 for what I came up with so far.

Ahh! You are correct. The example now more closely aligns with the test vector in the draft.

**Comment by michael-scharf** [comment]
Yep, but have you double-checked the example, most notably whether the key-chain is correct?

**Comment by mjethanandani** [comment]
> Yep, but have you double-checked the example, most notably whether the key-chain is correct?

@michael-scharf, I realize I need to give you both an ability to "compile" this draft. Currently, I am noticing issues with your commits. Ignore the paths as the are w.r.t. to my repositories. But it is your commit that I am validating. Once you have fixed them, I will rerun the tests and check the validity of the example.

Validating yang/ietf-tcp@2022-01-17.yang
yang/ietf-tcp@2022-01-17.yang:87: error: unterminated statement definition for keyword "description", looking at }
yang/ietf-tcp@2022-01-17.yang failed pyang validation

and these. Do not go by line numbers. But you know the text that you modified.

/Users/mahesh/git/personal/ietf-tcp/draft/draft-ietf-tcpm-yang-tcp-05.xml(302): Warning: Too long line found (L540), 1 characters longer than 72 characters: 
               "Identifies the address that is used by the local endpoint
/Users/mahesh/git/personal/ietf-tcp/draft/draft-ietf-tcpm-yang-tcp-05.xml(302): Warning: Too long line found (L548), 2 characters longer than 72 characters: 
               "Identifies the address that is used by the remote endpoint
/Users/mahesh/git/personal/ietf-tcp/draft/draft-ietf-tcpm-yang-tcp-05.xml(302): Warning: Too long line found (L556), 2 characters longer than 72 characters: 
               "Identifies the local TCP port used for the connection, and
/Users/mahesh/git/personal/ietf-tcp/draft/draft-ietf-tcpm-yang-tcp-05.xml(302): Warning: Too long line found (L572), 3 characters longer than 72 characters: 
               "Identifies the remote TCP port used for the connection, and

**Comment by michael-scharf** [comment]
Please check the latest commit in PR#73 (i.e., branch ietf-06-ms) again. I hope this fixes the issues.
