### ISSUE TITLE
Address YANG doctor comments

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-tcp#76]
Reviewer: Ebben Aries
Review result: On the Right Track

1 module in this draft:
- [ietf-tcp@2022-02-04.yang](mailto:ietf-tcp@2022-02-04.yang)

YANG compiler errors or warnings (pyang 2.5.2, yanglint 2.0.112, yangson 1.4.13)
- No compiler errors or warnings.  Instance data verified with features

Module [ietf-tcp@2022-02-04.yang](mailto:ietf-tcp@2022-02-04.yang):
- Overall the module is concise and conforms to the guidelines put forth in
 RFC8409.  Only a few minor nits as well as some comments and questions on
 the draft itself
- L#91 - Is there any reason to put a range that covers the entire uint8
 space?
- L#104 - Same as L#91

General comments on the draft/modules:
- The title is "A YANG Model for TCP Configuration" however the intent is to
 cover TCP connection tables and statistics.  While configuration parameters
 are introduced, is it not likely that as the model progresses will encompass
 additional state over time?  I would suggest readjusting wording to
 accomodate that this is not only geared towards configuration of TCP
 parameters (which multiple sections concentrate on) and more to TCP
 configuration, connection tables and state

- Section 3.3 - Tree Diagram.  If you are calling out this section is only for
 the abridged version you may want to include a reference to the full diagram
 in Appendix C

- Appendix B.2 - Use IPv6 addresses from the documentation prefixes defined
 inRFC3849 (draft-ietf-tcpm-ao-test-vectors should be updated accordingly as
 well)

- Understood that it is mentioned in the introduction this is a minimal set of
 features but statistics wise, there are currently only aggregate/global TCP
 statistics defined. Has there been any consideration for per-connection
 statistics and additional attributes much like outputs of `ss -tpi`
 (processes, counters, mss, pmtu, congestion ctl alg, etc..)? Or is the
 intent this will be served by a future version or separate
 module/augmentation at a later date?

**Comment by mjethanandani** [comment]
> Reviewer: Ebben Aries Review result: On the Right Track
> 
> 1 module in this draft:
> 
> * [ietf-tcp@2022-02-04.yang](mailto:ietf-tcp@2022-02-04.yang)
> 
> YANG compiler errors or warnings (pyang 2.5.2, yanglint 2.0.112, yangson 1.4.13)
> 
> * No compiler errors or warnings.  Instance data verified with features
> 
> Module [ietf-tcp@2022-02-04.yang](mailto:ietf-tcp@2022-02-04.yang):
> 
> * Overall the module is concise and conforms to the guidelines put forth in
>   RFC8409.  Only a few minor nits as well as some comments and questions on
>   the draft itself
> * L#91 - Is there any reason to put a range that covers the entire uint8
>   space?

I have no particular reason for putting the entire range, but I do not feel anything is wrong in keeping it also.

> * L#104 - Same as L#91
> 
> General comments on the draft/modules:
> 
> * The title is "A YANG Model for TCP Configuration" however the intent is to
>   cover TCP connection tables and statistics.  While configuration parameters
>   are introduced, is it not likely that as the model progresses will encompass
>   additional state over time?  I would suggest readjusting wording to
>   accomodate that this is not only geared towards configuration of TCP
>   parameters (which multiple sections concentrate on) and more to TCP
>   configuration, connection tables and state

Ok. I have added some text about both configuration and management of TCP.

> * Section 3.3 - Tree Diagram.  If you are calling out this section is only for
>   the abridged version you may want to include a reference to the full diagram
>   in Appendix C

Added some text about the full tree diagram.

> * Appendix B.2 - Use IPv6 addresses from the documentation prefixes defined
>   inRFC3849 (draft-ietf-tcpm-ao-test-vectors should be updated accordingly as
>   well)

I think this was discussed in one of the threads. I do not feel compelled to change the example.

> * Understood that it is mentioned in the introduction this is a minimal set of
>   features but statistics wise, there are currently only aggregate/global TCP
>   statistics defined. Has there been any consideration for per-connection
>   statistics and additional attributes much like outputs of `ss -tpi`
>   (processes, counters, mss, pmtu, congestion ctl alg, etc..)? Or is the
>   intent this will be served by a future version or separate
>   module/augmentation at a later date?

@michael-scharf , what is your take on it?

**Comment by michael-scharf** [comment]
Regarding per connection statistics: This is very implementation-specific and should be left for the future.

**Comment by michael-scharf** [comment]
As far as I can see, there are no pending issues here.
