### ISSUE TITLE
Address comments from Tom Petch

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-tcp#79]
Some stray thoughts.

All the IP address objects use the format that includes the zone; is this intended?

You mention the i2nsf-capability-data-model as an example of modelling TCP.  i2nsf-nsf-facing could be another.

The TLP in the YANG module is out of date (like the Copyright date).

The example uses port 80 which is traditionally insecure.  A secure port might set a better example.

**Comment by michael-scharf** [comment]
> All the IP address objects use the format that includes the zone; is this intended?

This is a good question. I am not sure whether it makes sense to explicitly remove the zone. My proposal is to keep as-is.

> You mention the i2nsf-capability-data-model as an example of modelling TCP. i2nsf-nsf-facing could be another.

Done in #88

> The TLP in the YANG module is out of date (like the Copyright date).

Done in #88

> The example uses port 80 which is traditionally insecure. A secure port might set a better example.

The keep-alive example needs thinking beyond this detail. I opened #89 specifically for this.

In a nutshell, I believe this issue can be closed.
