### ISSUE TITLE
IP addresses from draft-ietf-tcpm-ao-test-vectors

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-tcp#80]
This issue is to track the following thread

Med says:

`There is one minor comment about the ipv6 addresses in the examples: they should be derived from the prefix in RFC 3849. This should be fixed in draft-ietf-tcpm-ao-test-vectors (the same applies for 10.11.12.13, etcs that are not from the blocks defined in 5737). `

to which Joe objected:

```
I disagree. The addresses in test vectors are not examples for documentation, but rather an actual configuration intended for testing purposes.

I found only one other RFC that provides test vectors based on packet fields that include IP addresses: RFC 5769, but it (IMO) incorrectly uses the documentation addresses you suggest (I expect to submit an errata on that shortly - let me know if you know of others).
```

To which Michael suggested:

```
My proposal would be to await the IESG evaluation of draft-ietf-tcpm-ao-test-vectors. This detail is mentioned in my shepherd write-up as a heads-up.
 
If the addresses in draft-ietf-tcpm-ao-test-vectors have to be modified, the example in draft-ietf-tcpm-yang-tcp will change as well.
```

**Comment by michael-scharf** [comment]
RFC 9235 was published with the proposed addresses not taken from RFC 3849 and 5737 (see https://www.rfc-editor.org/rfc/rfc9235.html).

If the document should stay consistent with the example from RFC 9235, the IP addresses do not have to be changed.

But we could add one additional sentence to explain the value of the addresses, see #88.

**Comment by michael-scharf** [comment]
Mahesh, any thoughts?

**Comment by mjethanandani** [comment]
Agree. I can add the one sentence to explain as much.

**Comment by michael-scharf** [comment]
I have already committed a sentence in #88. I believe this issue can be closed.
