### ISSUE TITLE
Fix authentication model

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-tcp#83]
The current TCP model does not have any reference to a keychain model to allow for configuration of the keychain. This issue tries to address it.

**Comment by mjethanandani** [comment]
Examples of TCP-AO configurations

TCPM presentation from Juniper and Nokia: 
https://datatracker.ietf.org/meeting/112/materials/slides-112-tcpm-tcp-ao-interop-and-some-exciting-news-02

Examples for Cisco, Juniper, and Nokia: 
https://github.com/TCP-AO/Configuration-examples

Further presentations can be found at https://github.com/TCP-AO and 
https://www.tcp-ao.net/, including reference to 
https://www.juniper.net/documentation/us/en/software/junos/transport-ip/topics/topic-map/tcp-configure-ao-bgp-ldp.html

**Comment by michael-scharf** [comment]
PR #84 adds the reference, i.e., this individual issue can probably be closed. There are other related aspected, which may be better tracked by #87.
