### ISSUE TITLE
 Reuse the TCP model in the BMP mode: Default for 4 tuple

### ISSUE THREAD

**Issue by michael-scharf** [mjethanandani/ietf-tcp#85]
Comment 1 from Camilo Cardona:

Regarding the 4-tuple connection, in BMP, we would like to have a “default” case in which the configured device connects to another using ip/port (i.e. active case),  but also to provide the option of expecting the  tcp connection over a local ip/port (i.e. passive case). We might need our own container for this.

**Comment by michael-scharf** [comment]
I have already proposed on the TCPM list not to change the document because of this request, since this is a quite specific use case.

In other words, I believe this issue can be closed without any further action. Other thought?

**Comment by mjethanandani** [comment]
Agree. We can close it.
