### ISSUE TITLE
Use of Keep-alives

### ISSUE THREAD

**Issue by michael-scharf** [mjethanandani/ietf-tcp#89]
The use of keep-alives and the references to draft-ietf-netconf-tcp-client-server-12 need further thinking.

1. Keep-alives are a seldomly used TCP feature that is optional to implement. Is this really relevant to be included in this model?
2. Removing keep-alives (and the example) would remove the dependency to draft-ietf-netconf-tcp-client-server-12. Note that users of keep-alives could still use draft-ietf-netconf-tcp-client-server as needed.
4. A specific comment from Tom Petch on the keep-alive example: "The example uses port 80 which is traditionally insecure. A secure port might set a better example." If the example stays in the document, probably an alternative to port 80 should be used, as keep-alives are more typical for long-lived connections (e.g., port 22).

**Comment by mjethanandani** [comment]
We can change the port number to 22 to address Tom's issue. 

I talked to Kent recently, and he said he is ready for the document to be published as a RFC.

I think the requirement for keep-alive comes from NETCONF itself, which needs a long-lived connection.

**Comment by michael-scharf** [comment]
The change to port 22 is discussed as part of PR #96 and thus handled there.
